# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="NetBroPro"
CIRCUITPY_WIFI_PASSWORD="Prince123"

# To enable modifying files from the web. Change this too!
# Leave the User field blank when you type the password into the browser.
CIRCUITPY_WEB_API_PASSWORD="ESP32S3"

CIRCUITPY_WEB_API_PORT=80

CIRCUITPY_DISABLE_INTERNAL_DISPLAY=1
