CIRCUITPY_WIFI_SSID="your-ssid"
CIRCUITPY_WIFI_PASSWORD="your-password"
ADAFRUIT_AIO_USERNAME="your-username"
ADAFRUIT_AIO_KEY="your-aio-key"
TIMEZONE="Region/City"
CIRCUITPY_WEB_API_PASSWORD="change-me"
CIRCUITPY_WEB_API_PORT=80
